package com.adrplatform.auth.config;

import com.github.benmanes.caffeine.cache.Caffeine;
import org.springframework.cache.CacheManager;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.cache.caffeine.CaffeineCacheManager;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.concurrent.TimeUnit;

@Configuration
@EnableCaching
public class CacheConfig {

    /**
     * Cache for AI insights generated by AiInsightService.
     * TTL: 2 hours — ADR content rarely changes during a session.
     * Max size: 500 entries — prevents unbounded memory growth.
     * Eviction: when the ADR is updated, the cache entry is explicitly evicted
     * via @CacheEvict in AdrService.updateAdr().
     */
    @Bean
    public CacheManager cacheManager() {
        CaffeineCacheManager manager = new CaffeineCacheManager("ai-insights");
        manager.setCaffeine(
            Caffeine.newBuilder()
                .expireAfterWrite(2, TimeUnit.HOURS)
                .maximumSize(500)
        );
        return manager;
    }
}
